algolia/create-instantsearch-app

- bin/create-instantsearch-app.js
- boilerplates/instantsearch.js/app.js.hbs
- boilerplates/instantsearch.js/main.css
- Add mainAttribute option
- Use mainAttribute to display example of results
- Highlight results
- Update CSS for highlighting and to match is.js colors
> [feat] add main attribute option for init prompt

- boilerplates/instantsearch.js/index.html.hbs
- Update instantsearch.js to 2.1.2
- Update instantsearch CSS to 2.1.2
> [feat] update dependencies

- .prettierrc
- README.md
- bin/create-instantsearch-app.js
- lib/createProject.js
- package.json
- yarn.lock
As part of a PR series, I ran Prettier as a single PR.
I also fixed the command to run `create-instantsearch-app` with Yarn (the name of the project was missing).
> Run prettier

- templates/InstantSearch.js/index.html.hbs
- templates/InstantSearch.js/src/app.css
- templates/InstantSearch.js/src/index.css
I tried to go for an OK-looking design without too much code. It should eventually be consistent with all other templates (except the header color).
Let me know if this is a good base for other templates or if we should go for something different.
> feat(v3): Improve InstantSearch.js template

- README.md
🔗 [**Read documentation**](https://github.com/algolia/create-instantsearch-app/blob/docs/readme/README.md)
> docs(readme): Update documentation

- README.md
- packages/cli/cli.js
- packages/create-instantsearch-app/CreateInstantSearchApp.js
- packages/create-instantsearch-app/CreateInstantSearchApp.test.js
- packages/create-instantsearch-app/__snapshots__/CreateInstantSearchApp.test.js.snap
- packages/shared/__snapshots__/utils.test.js.snap
- packages/shared/utils.js
- packages/shared/utils.test.js
- packages/tasks/common/build.js
Read [the Templates section](https://github.com/algolia/create-instantsearch-app/blob/feat/custom-templates/README.md#templates) for more info.
>  feat: Add support for custom templates

- README.md
> docs(readme): Update template note on Handlebars

- packages/cli/cli.js
- packages/tasks/node/teardown.js
If generating the app `my-app-4` from `/tmp/apps`, recommend to change directory to:
- Before: `/tmp/apps/my-app-4`
- After: `my-app-4`
> feat(cli): Print relative cd path

- scripts/__snapshots__/e2e-templates.test.js.snap
- src/templates/React InstantSearch/.template.js
- src/templates/React InstantSearch/package.json
- src/templates/React InstantSearch/src/App.js.hbs
**Summary**
Use the new package rather than the legacy one.
> refactor: use react-instantsearch-dom rather than react-instantsearch

- README.md
> docs(readme): Add iOS and Android templates

- .travis.yml
This should speed up Travis builds.
> ci(travis): Cache CocoaPods

- scripts/__snapshots__/e2e-templates.test.js.snap
- scripts/e2e-templates.test.js
>  test(e2e): Snapshot partial dependencies

- scripts/e2e-installs.test.js
This PR adds more confidence by asserting that all templates get installed correctly (with Node and iOS templates).
> test(e2e): Test installation for all templates

- src/cli/index.js
With this change, we provide more information about what we're talking about and what is the goal of the question :)
> fix(cli): provide more context to user for searchable attribute

- CONTRIBUTING.md
- Add more info on releasing
- Add section on updating templates on CodeSandbox
> docs(contributing): update instructions

- .travis.yml
This will boost the CI checks.
> ci(travis): Drop Node 9

- scripts/__snapshots__/e2e-templates.test.js.snap
- src/templates/InstantSearch.js/index.html.hbs
- src/templates/InstantSearch.js/src/app.css
- src/templates/InstantSearch.js/src/app.js.hbs
> feat(js): migrate template to InstantSearch.js 3

- scripts/release-templates.js
This adds support for releasing earlier templates on CodeSandbox (e.g. InstantSearch.js 2).
<details>
<summary>Dry run of what applications are created</summary>
```
{ name: 'instantsearch-android-app',
template: 'InstantSearch Android',
libraryVersion: undefined,
appId: 'latency',
apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
indexName: 'instant_search',
attributesToDisplay: [ 'name', 'description' ],
attributesForFaceting: [ 'brand' ],
installation: false,
silent: true }
{ name: 'instantsearch-ios-app',
template: 'InstantSearch iOS',
libraryVersion: undefined,
appId: 'latency',
apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
indexName: 'instant_search',
attributesToDisplay: [ 'name', 'description' ],
attributesForFaceting: [ 'brand' ],
installation: false,
silent: true }
{ name: …
```
> chore(release): support earlier template versions on CodeSandbox

- scripts/__snapshots__/e2e-templates.test.js.snap
- src/templates/React InstantSearch/src/App.js.hbs
cc @biletron
@francoischalifour, do you think the double brace could confuse handlebars?
> fix(React InstantSearch): placeholder template

- .release-it.json
- package.json
- yarn.lock
This updates `release-it` to v1. I applied the changes based on my previous work on my [Medium Zoom](https://github.com/francoischalifour/medium-zoom/pull/89/files#diff-96cea31a3f172eceff190594eda05560) library.
> chore(deps): update release-it to v1 (major)

- package.json
- renovate.json
This moves the Renovate configuration to its own file.
> chore(renovate): create config file

- jest.config.js
- package.json
This moves the Jest configuration to its own file.
> chore(jest): create config file

- src/templates/Autocomplete.js/package.json
- src/templates/InstantSearch.js 2/package.json
- src/templates/InstantSearch.js/package.json
- src/templates/JavaScript Client/package.json
- src/templates/JavaScript Helper 2/package.json
- src/templates/JavaScript Helper/package.json
Ran into this issue when creating a new app today: https://github.com/parcel-bundler/parcel/issues/5943
Fix was to update to latest version of Parcel 1...I did a find/replace for past version.
> fix(templates): update to latest Parcel version

- e2e/__snapshots__/templates.test.js.snap
- src/templates/InstantSearch.js widget/.prettierrc
This PR adds `.prettierrc` to InstantSearch.js widget template.
> chore(templates): add .prettierrc to js widget template

- package.json
- src/cli/__tests__/getFacetsFromIndex.test.js
- src/cli/__tests__/getInformationFromIndex.js
- src/cli/getAttributesFromIndex.js
- src/cli/getFacetsFromIndex.js
- src/cli/getInformationFromIndex.js
- src/cli/index.js
- src/templates/InstantSearch.js/.template.js
- src/templates/InstantSearch.js/src/app.js.hbs
- src/templates/React InstantSearch/.template.js
- src/templates/React InstantSearch/src/App.js.hbs
- src/templates/Vue InstantSearch/.template.js
- src/templates/Vue InstantSearch/src/App.vue
- yarn.lock
- add "flags" to the template that can be checked in the app.js
- enable dynamic widgets if version is new enough
- add a configure widget with facets: [*] + maxValuesPerFacet to avoid second request
> feat(facets): use dynamicWidgets

- e2e/__snapshots__/templates.test.js.snap
- src/templates/React InstantSearch/.template.js
- src/templates/React InstantSearch/src/App.js.hbs
- src/templates/Vue InstantSearch/.template.js
- src/templates/Vue InstantSearch/src/App.vue
> feat(templates): use non-experimental dynamic widgets
