algolia/create-instantsearch-app

boilerplates/instantsearch.js/package.json.hbs
- Update `start` command to enable live-reloading with the dev server
=> [feat] replace http-server by browser-sync

bin/create-instantsearch-app.js, boilerplates/instantsearch.js/index.html.hbs, config/index.js, lib/fetchVersions.js, package.json
This feature is needed for a guide I'm working on 😁
* Fetch instantsearch.js version based on the `npm-search` Algolia index
* Add prompt choice to use the instantsearch.js version (defaults to the latest one), rejects if the version doesn't exist
* If offline, default the instantsearch.js@2 (jsDelivr resolves it to the actual latest version, `2.4.1` as of now)
* Inject the version in the HTML template
Let me know if there are other ways to solve it!
*Note: Node >= 7.6 is necessary because I've used `async` functions.*
=> feat(version): add dynamic versioning

src/createInstantSearchApp.js, src/utils.js, src/utils.test.js
This PR adds support for option override from the command-line for the v3.
```sh
create-instantsearch-app my-app --indexName MY_INDEX_NAME --template "InstantSearch.js"
```
Will not ask for `indexName` and `template` in the menu:
This is needed for compiling templates to demos.
=> feat(v3): Add support for option override

src/createInstantSearchApp.js, templates/InstantSearch.js/index.html.hbs, templates/InstantSearch.js/src/app.js.hbs
```js
// app.js
search.addWidget(
instantsearch.widgets.refinementList({
container: '#location-list',
attributeName: 'location',
})
);
search.addWidget(
instantsearch.widgets.refinementList({
container: '#brand-list',
attributeName: 'brand',
})
);
```
```html
<div id="location-list">
<div id="brand-list">
```
=> feat(v3): Add facets option in menu

package.json, src/createInstantSearchApp.js, src/utils.js, src/utils.test.js, tasks/fetchLibraryVersions.js, templates/InstantSearch.js/index.html.hbs, yarn.lock
This PR adds support for the `libraryVersion` option which allows the user to select a specific version of the InstantSearch flavor used.
This feature allows us to reproduce reported bugs more easily by choosing a specific InstantSearch version for the app.
I used the `npm-search` index to get all versions of the selected flavor, and get the latest stable version with [latest-semver](https://github.com/sindresorhus/latest-semver) (which is the default version of any app created).
Happens when offline for instance (`AlgoliaSearchNetworkError` might be raised).
The fallback strategy is to install the version `1.0.0`, which is not great. Any idea to improve this fallback strategy?
=> feat(v3): Add option to select InstantSearch version

README.md
I updated the getting started with the [`npm-init <@scope>` ](https://docs.npmjs.com/cli/init) command.
[Link to the section](https://github.com/algolia/create-instantsearch-app/blob/docs/readme-npm-usage/README.md#get-started)
=> docs(readme): Update npm usage with `npm init`

.gitignore, scripts/__snapshots__/e2e-templates.test.js.snap, templates/Angular InstantSearch/src/app/app.component.css, templates/Angular InstantSearch/src/app/app.component.html.hbs, templates/InstantSearch.js/index.html.hbs, templates/InstantSearch.js/src/app.css, templates/InstantSearch.js/src/app.js.hbs, templates/React InstantSearch/src/App.css, templates/React InstantSearch/src/App.js.hbs, templates/Vue InstantSearch/src/App.vue
When we don't provide any `attributesForFaceting` the templates generate an empty `div`. 
This PR remove this `div` when no facets are provided.
=> fix: templates without facets

packages/tasks/common/build.js, scripts/__snapshots__/e2e-templates.test.js.snap, templates/InstantSearch.js/.editorconfig, templates/InstantSearch.js/.eslintignore, templates/InstantSearch.js/.eslintrc.js, templates/InstantSearch.js/.prettierrc, templates/InstantSearch.js/package.json, templates/InstantSearch.js/src/app.js.hbs, templates/React InstantSearch/.editorconfig, templates/React InstantSearch/.eslintrc.js, templates/React InstantSearch/.prettierrc, templates/React InstantSearch/package.json, templates/Vue InstantSearch/.editorconfig, templates/Vue InstantSearch/.eslintrc.js, templates/Vue InstantSearch/package.json
=> feat(templates): Add config files

packages/tasks/node/install.js
When hitting <kbd>Ctrl</kbd> <kbd>C</kbd> (sending the signal `SIGINT`), it is unnecessary and counter-intuitive to log the error during the installation step.
=> feat(task): Ignore error log when user aborts during installation

packages/cli/cli.js
This PR reorders the questions in the CLI and prints recommended attributes to display in the hits.
These recommended attributes are based on the highlightable attributes in the dashboard, gotten with a search on the index. They default to a selection among `['title', 'name', 'description']`. These values are bumped up in the ranking of the list since they are the most commonly used.
If there's a missing information to target the index (`appId`, `apiKey` or `indexName`), we skip the question. If the index is not reachable, we print the default list.
---
Closes #32
=> feat(cli): Recommend attributes to display in hits

README.md
We claim to support Node 8 but `npm init <package>` is not supported from this version.
=> docs(readme): Use `npx` instead of `npm init`

packages/cli/cli.js
When the stable version is not available (only beta version are published) the script fail. In case we don't have a stable version fallback to the latest one.
**Before**
**After**
=> fix(cli): fallback on latest version when stable unavailable

README.md
This note still mentions `npm init` although we document `npx` now.
We already document that the tool only works with Node >= 8 (which comes with `npx` packaged), so we don't need that note.
=> docs(readme): Remove remaining note on `npm init`

templates/React InstantSearch Native/.template.js
Since `attributesForFaceting` is not supported by the React Native template, warn the user about it.
=> feat(templates): Warn facets usage with React Native template

.gitignore, src/cli/__tests__/getConfiguration.test.js, src/cli/getConfiguration.js
**Summary**
When we provide a template directly from the CLI we don't let the user choose the version. By default we pick the latest `stable` version available. When there is no `stable` available Yarn will ask for which version you want to install but the template is generated with an empty version. 
This PR fix this issue by taking the latest version available in case the latest `stable` is not available. I also added the folder `sample` to the `.gitignore` to test the CLI with this folder name. We can test the template generation without pollute the git diff.
**Before**:
```json
{
"dependencies": {
"react-instantsearch-native": "^"
}
}
```
**After**:
```json
{
"dependencies": {
"react-instantsearch-native": "^5.2.0-beta.1"
}
}
```
=> fix(cli): use latest version when stable unavailable

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- Bug report
- Feature request
=> chore(github): Add issue templates

src/tasks/ios/install.js
**Summary**
In case it's your first install of CocoaPods (like me) the command will fail. We can run the command (see below) before each install.
```sh
pod repo update
```
Is it a problem @spinach?
=> fix(ios): run pod repo update before install

src/tasks/ios/teardown.js
There's no need to `try/catch` since nothing can fail during this task (originally taken from [Node's teardown task](https://github.com/algolia/create-instantsearch-app/blob/6e27ec3cb525696fe5646ac9d03f87b3eac702d5/src/tasks/node/teardown.js)).
=> refactor(tasks): Simplify teardown task for iOS

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/Angular InstantSearch/package.json, src/templates/React InstantSearch Native/package.json, src/templates/React InstantSearch/package.json, src/templates/Vue InstantSearch/package.json
Dynamic dependency versions for `libraryName` were not pinned.
=> fix(templates): Pin library dependencies

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/React InstantSearch/package.json, src/templates/React InstantSearch/src/App.js.hbs
Now that we are using `react-instantsearch-dom` we can use by default the `searchClient`. The prop is available since the version `5.1.0` and the first version of the package is `5.2.0`. No changes are required for React InstantSearch Native because the current version already use the `searchClient`.
=> feat(templates): use searchClient in React

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/Angular InstantSearch/package.json, src/templates/Angular InstantSearch/src/app/app.component.ts
=> feat(templates): Use `searchClient` in Angular

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/Angular InstantSearch/src/app/app.component.spec.ts
Default tests were previously failing because Angular didn't know the InstantSearch components.
=> fix(templates): Fix default failing tests in Angular

.travis.yml
Travis failed because its default limit is 10 minutes. The end-to-end tests take more time now because we test all templates' installation and build.
See: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
=> ci(travis): Allow E2E tests to take up to 20 minutes

scripts/e2e-installs.test.js
Run `yarn build` after app generation to make sure that the app is runnable. This will prevent us from merging failing PRs from Renovate (because of incompatible dependencies).
=> test(e2e): Make sure that apps are runnable after generation

CONTRIBUTING.md, README.md, docs/custom-templates.md, docs/deploy.md, package.json
Add tutorials for:
- Creating a custom template
- Deploying an InstantSearch App
I decided to undocument `createInstantSearchApp(path, options?, tasks?)` in favor of `createInstantSearchApp(path, options?)` and creating custom templates directly.
Closes #152.
=> docs: Add tutorials

package.json
This way it does not load jsdom (which we don't use here). Also the latest jsdom generates security issues, but since we do not want jsdom for this project, we should not even be bothered.
https://github.com/facebook/jest/issues/6766
=> chore(jest): provide node environment

src/templates/React InstantSearch Native/package.json
This reverts commit 28266580c7b7395ae8cd959931e64c03b5efacad.
> Expo SDK v29.0.0 is once again based on React Native 0.55.4.
[See reference](https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf)
=> revert: fix(deps): update dependency react-native to v0.56.0 (#193)

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/Vue InstantSearch/package.json, src/templates/Vue InstantSearch/src/App.vue, src/templates/Vue InstantSearch/src/main.js
As spotted in #239, the Vue template needs `eslint-plugin-vue` to work correctly.
This PR also makes the template ESLint compliant.
=> fix(templates): Add Vue ESLint config

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/InstantSearch.js/src/app.js.hbs
This PR disable the `autofocus` option for InstantSearch. When you are working on an App or on CodeSandbox the SearchBox get the focus on each reload. It's a bit frustrating.
=> fix(InstantSearch): disable autofocus

src/cli/index.js
Uses the [inquirer](https://www.npmjs.com/package/inquirer) default value feature
closes #290
=> feat(cli): add default Algolia credentials

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/React InstantSearch/package.json
- Update to `react-scripts@2`
- Update React version
- Update React DOM version
- Add `browserslist` for `react-scripts@2`
- Downgrade ESLint to 5.6.0 as a requirement to `react-scripts@2`
=> feat(react): upgrade to react-scripts@2

package.json
The previous script generated all the changelog every time the command was run.
=> chore(changelog): don't generate whole changelog

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/Angular InstantSearch/angular.json
I found out about this while writing the customization guide for angular.
Right now it seems we don't adovcate for using `instantsearch.css` styles directly.
After this is merged, we'd need to release and regenerate the samples in https://github.com/algolia/doc-code-samples/tree/master/Angular%20InstantSearch
=> fix(angular): use instantsearch.css styles directly

src/api/check-config.js, src/api/index.js
This is a refactor that moves `checkConfig()` to its own file.
=> refactor(api): export configuration checker

scripts/e2e-installs.test.js, src/api/check-config.js, src/utils/index.js
The template paths are given with relative paths to the API, so adding `path.resolve` makes sure that the path becomes absolute and exists.
I added an end-to-end test with a relative path to make sure it's resolved.
This should close #364.
=> fix(api): resolve relative paths

scripts/__snapshots__/e2e-templates.test.js.snap, src/templates/React InstantSearch Native/.babelrc.template, src/templates/React InstantSearch Native/app.json, src/templates/React InstantSearch Native/babel.config.js, src/templates/React InstantSearch Native/package.json
The template for React Native was not working anymore. I've updated it to use Expo rather than `create-react-native-app`. CRNA [have been deprecated](https://github.com/react-community/create-react-native-app) for the Expo version.
=> fix(templates): use expo for react-native

e2e/__snapshots__/templates.test.js.snap, package.json, src/tasks/node/teardown.js, src/templates/InstantSearch.js 2/src/app.js.hbs, src/templates/InstantSearch.js/src/app.js.hbs, src/templates/JavaScript Client/src/app.css, src/templates/JavaScript Helper/src/app.css, yarn.lock
A common issue with dynamic values injected in the templates is that generated files were not always Prettier-compliant. For instance, if an attribute name or an index name are longer than anticipated, they should be on multiple lines.
This PRs aims a solving this issue by running Prettier at the `teardown` hook. Prettier is run from the Create InstantSearch App dependency, but run with the templates local `.prettierrc` configuration. This therefore respects the configuration specified in the template.
You can see the results in the snapshots generated.
=> feat(api): run Prettier after templates generation

.circleci/config.yml
In #394 we changed the E2E process to build apps on the CI and only run the E2E tests regarding the templates generation. This also adds the [E2E tests regarding the app installation generation](https://github.com/algolia/create-instantsearch-app/blob/26f8f8c621f21b29e2d2caf22a0ab648a8874a06/e2e/installs.test.js) (decoupled with building all apps).
=> chore(ci): run complete E2E test suite

src/templates/Vue InstantSearch 1/package.json, src/templates/Vue InstantSearch/package.json
This fixes the wrongly updated Vue CLI dependencies which are not compatible.
=> chore(deps): fix vue-cli deps

e2e/__snapshots__/templates.test.js.snap, src/templates/InstantSearch.js/src/app.js.hbs
This updates the InstantSearch.js 3 template with a newer syntax that we recommend for InstantSearch.js 4.
This has the benefits of also working with v4, and therefore we won't need to create another template.
=> fix(templates): prepare InstantSearch template for v4

src/templates/InstantSearch.js/.template.js
This allows to use the InstantSearch.js template with the newly released InstantSearch.js 4.
=> feat(templates): allow InstantSearch.js template with v4

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch/src/App.js.hbs
This updates the React template to a more modern way with a function component. We use React 16.12.0 where hooks are available, so there's no need for a class.
=> fix(templates): use function component in React template

e2e/__snapshots__/templates.test.js.snap, src/templates/Autocomplete.js/package.json, src/templates/InstantSearch.js 2/package.json, src/templates/InstantSearch.js/package.json, src/templates/JavaScript Client/package.json, src/templates/JavaScript Helper 2/package.json, src/templates/JavaScript Helper/package.json, src/templates/React InstantSearch/package.json, src/templates/Vue InstantSearch 1/package.json, src/templates/Vue InstantSearch/package.json
When going to a [template URL](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js), CodeSandbox doesn't always display the most relevant file on the default code view. In this template, we'd like to be directed to `src/app.js`. This PR addresses that problem on templates that CodeSandbox supports.
This adds a [`main`](https://docs.npmjs.com/files/package.json#main) entry point to all templates for which `main` is supported (Angular InstantSearch `app.component.html` is not supported by CodeSandbox).
=> fix(templates): add `main` entry point

package.json, yarn.lock
This updates the Jest dependencies of the repo.
The main benefit on this repo is the [new colors](https://jestjs.io/blog/2020/01/21/jest-25#colors-of-differences-when-snapshot-tests-fail) that will make it easier to see the differences in the templates snapshots. We can also hope for the tests to run a bit faster with this upgrade.
Note that Renovate seems to be broken on this repo since we had to force push on `master`.
=> chore(deps): update dependency jest to v25

e2e/__snapshots__/templates.test.js.snap, scripts/release-templates.js, src/templates/Autocomplete.js/index.html.hbs, src/templates/Autocomplete.js/package.json, src/templates/Autocomplete.js/src/app.css, src/templates/Autocomplete.js/src/app.js.hbs, src/templates/Autocomplete.js/src/index.css
This updates the Autocomplete.js template to the new Satellite theme.
- Use InstantSearch Satellite theme
- Update the dropdown style to match the design system
- Change the Algolia index to a query suggestions index on the CodeSandbox deployment
- Use latest Algoliasearch v3 (v4 is not compatible)
- Reformat JS to be easier to interact in CodeSandbox
- Add debug mode in development (handy on CodeSandbox because Parcel is in development mode there)
- Update dependencies
- [Check on CodeSandbox](https://codesandbox.io/s/n91c2)
=> feat(templates): update Autocomplete.js template to Satellite

e2e/__snapshots__/templates.test.js.snap, e2e/templates.test.js, src/cli/getConfiguration.js, src/cli/index.js, src/templates/InstantSearch.js widget/.template.js, src/templates/React InstantSearch widget/.template.js
This PR adds `packageNamePrefix` to the widget templates.
For example, when the project name is `test`, it becomes like this:
* the package name for InstantSearch.js widget: `@user-scope/instantsearch-widget-test`
* the package name for React InstantSearch widget: `@user-scope/react-instantsearch-widget-test`
`appName` config in the widget templates are actually almost useless, because `packageName` is used instead. It's only used in snapshot tests.
To make the snapshots more readable/meaningful, I changed the value of `appName` for both InstantSearch.js widget and React InstantSearch widget and thus, the snapshots have change quite a lot in this PR.
=> fix(templates): add `packageNamePrefix` to widget templates

e2e/installs.test.js, e2e/templates.test.js, scripts/build-app.js, src/cli/index.js
* This PR makes <project directory> argument optional.
(`npx create-instantsearch-app` will asks for the directory)
* After inferring project name from the directory, it asks if you want to name it differently.
(path provided)
```
$ npx create-instantsearch-app ~/workspace/date-picker
The name of the application or widget: [date-picker]
```
`date-picker` is given as a default name but you can change there.
(path not provided)
```
$ npx create-instantsearch-app
Project directory: 
```
Let's say you typed `date-picker`, then the next step would be:
```
The name of the application or widget: [date-picker]
```
The name is inferred from the path but again lets you update it.
=> feat(cli): make app path optional

e2e/__snapshots__/templates.test.js.snap, src/templates/InstantSearch.js widget/CONTRIBUTING.md, src/templates/InstantSearch.js widget/README.md, src/templates/InstantSearch.js widget/example/index.css, src/templates/InstantSearch.js widget/example/index.html, src/templates/InstantSearch.js widget/example/index.ts.hbs, src/templates/InstantSearch.js widget/src/index.ts.hbs, src/templates/InstantSearch.js widget/src/renderer.ts.hbs, src/templates/InstantSearch.js widget/src/types.ts.hbs
=> feat(js-widget): add example

e2e/__snapshots__/templates.test.js.snap, src/templates/InstantSearch.js widget/.template.js, src/templates/InstantSearch.js widget/package.json.hbs, src/templates/InstantSearch.js widget/src/types.ts.hbs
This makes the TS integration no longer need `experimental-typescript`
=> feat(is widget): upgrade to standard types

e2e/__snapshots__/templates.test.js.snap, src/templates/InstantSearch.js/index.html.hbs, src/templates/InstantSearch.js/package.json, src/templates/InstantSearch.js/src/global.d.ts.hbs, src/templates/InstantSearch.js/tsconfig.json
Since https://github.com/algolia/instantsearch.js/pull/4844 the UMD has type definitions exposed, which we can use in codesandbox, even when the file itself isn't written in TypeScript, or using modules
=> feat(js): add typescript to the js template

src/templates/Vue InstantSearch/.template.js
not yet added a new template for Vue 3, that can be done later by @eunjae-lee, but this template doesn't touch any of the breaking changes in v4
This PR fixes CI
=> feat(vue): support Vue InstantSearch 4

e2e/__snapshots__/templates.test.js.snap, src/templates/Angular InstantSearch/tsconfig.json
This works around a problem you can encounter on codeandbox.
Could using client-search instead of algoliasearch/lite better solve this problem? @Haroenv @francoischalifour 
```
lite_1.default is not a function
```
=> fix(Angular IS): enable esModuleInterop

e2e/__snapshots__/templates.test.js.snap, src/templates/Angular InstantSearch/angular.json, src/templates/Angular InstantSearch/src/index.html
Using CSS from node_modules is causing problems with CodeSandbox
cf. https://github.com/codesandbox/codesandbox-client/issues/6235
=> fix(angular): replace css imports with CDN <link>s

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch/src/App.js.hbs
This PR adds a missing import that prevented the React template for working in the latest release.
=> fix(react): add missing configure widget import

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch Native/App.js.hbs, src/templates/React InstantSearch Native/app.json, src/templates/React InstantSearch Native/package.json, src/templates/React InstantSearch Native/src/InfiniteHits.js.hbs, src/templates/React InstantSearch Native/src/SearchBox.js.hbs
Current version fails to run (at least on my machine, might be related to the M1 arch). Updating all dependencies fixed the issue.
Took the opportunity to make `App` a function component as a basis for an update to the getting started doc (https://github.com/algolia/doc/pull/6538).
=> fix(react-native): update template and related dependencies

package.json, src/templates/Angular InstantSearch/package.json, src/templates/Autocomplete/package.json, src/templates/InstantSearch.js widget/package.json.hbs, src/templates/InstantSearch.js/package.json, src/templates/JavaScript Helper 2/package.json, src/templates/React InstantSearch Native/package.json, src/templates/React InstantSearch widget/package.json.hbs, src/templates/React InstantSearch/package.json, src/templates/Vue InstantSearch 2/package.json, src/templates/Vue InstantSearch/package.json, yarn.lock
This sets all templates (except Autocomplete 0.x and Helper 1) to use `algoliasearch@4`.
I've used a version range instead of pinning so we don't have to keep this up to date whenever we release `algoliasearch`. This seems fine since this is a dependency we fully control. Let me know if there are any reasons not to.
=> chore: set algoliasearch to latest major range

src/templates/Angular InstantSearch/package.json
types/algoliasearch isn't needed, and not used either, so can safely be removed from the starter
=> fix(angular): remove @types/algoliasearch dep

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch/src/App.js.hbs
**Problem**
When choosing dynamic widgets setup, the fallback component (RefinementList) is not imported 
**Offending line**
https://github.com/algolia/create-instantsearch-app/blob/efda5395cef7865c7b4cebe741e7ab5e8ea4b2f8/src/templates/React%20InstantSearch/src/App.js.hbs#L45
**Error message**
**Solution**
Add to conditional import section for dynamic widgets to include RefinementList
=> fix(React InstantSearch): import RefinementList if DynamicWidgets used

.gitignore
This ignores local `.env` files in version control.
=> chore: ignore .env file

e2e/__snapshots__/templates.test.js.snap, src/templates/Vue InstantSearch with Vue 3/package.json, src/templates/Vue InstantSearch with Vue 3/vite.config.js
This small PR adds `@vitejs/plugin-vue-jsx` as a dependency for the **Vue InstantSearch with Vue 3** template, in order to correctly parse and transform JSX input.
=> fix(Vue 3): add vite plugin to correctly handle jsx

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch widget/README.md, src/templates/React InstantSearch widget/package.json.hbs, src/templates/React InstantSearch widget/src/lib/connector.ts.hbs, src/templates/React InstantSearch widget/src/lib/widget.tsx.hbs, src/templates/React InstantSearch widget/src/types/connector.ts
This PR adds support for `$$type` and `$$widgetType` in the **React InstantSearch Widget** template. It also addresses some build issues.
Ticket: [FX-993](https://algolia.atlassian.net/browse/FX-993)
**Result**
- The widget template now sets `$$type` and `$$widgetType` (to `{{ organization }}.{{ widgetName }}` by default)
- The build script doesn't fail anymore due to TypeScript issues
- The README correctly shows how to import `InstantSearch` from `react-instantsearch-dom`
=> feat(react instantsearch widget): add connector and widget metadata

e2e/__snapshots__/templates.test.js.snap, src/templates/Angular InstantSearch/src/app/app.component.html.hbs, src/templates/InstantSearch.js/index.html.hbs, src/templates/InstantSearch.js/src/app.js.hbs, src/templates/React InstantSearch Hooks/src/App.tsx.hbs, src/templates/React InstantSearch/public/index.html, src/templates/React InstantSearch/src/App.js.hbs, src/templates/Vue InstantSearch with Vue 3/index.html, src/templates/Vue InstantSearch with Vue 3/src/App.vue, src/templates/Vue InstantSearch/public/index.html, src/templates/Vue InstantSearch/src/App.vue
This PR brings a few small improvements to the templates:
- it showcases the use of another widget
- it prevents scrolling too far to see the pagination
- it improves the user experience when multiple facets are chosen during the template configuration
- it unifies the style of the templates
These changes only apply to those templates:
- Angular InstantSearch
- InstantSearch.js
- React InstantSearch
- React InstantSearch Hooks
- Vue InstantSearch
- Vue InstantSearch with Vue 3
=> feat(templates): various improvements

.github/workflows/release.yml, README.md, scripts/release-templates.js, ship.config.js
Currently, Shipjs is set up to run a `afterPublish` script to update the templates after the package is published on npm. This step [currently fails in CI](https://app.circleci.com/pipelines/github/algolia/create-instantsearch-app/2266/workflows/086c8f7c-6d5a-472e-8e76-b1bfa63fb17e/jobs/10893?invite=true#step-106-380) for unknown reasons, and prevents the execution of the following steps (git tag and git release). 
~This PR temporarily disables this script execution until a solution is found. This means that until this is solved, we should manually update the templates by running `yarn release-templates` locally.~
> **Note**
> I tried multiple approaches to debug the issue but could not reproduce it locally so I pivoted to set up a GitHub Action that will perform the update instead. The …
=>  chore(ci): perform template update from github action

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch Hooks/package.json, src/templates/React InstantSearch Hooks/src/App.tsx.hbs, src/templates/React InstantSearch Hooks/src/Panel.tsx, src/templates/React InstantSearch Hooks/src/index.tsx, src/templates/React InstantSearch/package.json, src/templates/React InstantSearch/src/index.js
Ticket: [FX-1586](https://algolia.atlassian.net/browse/FX-1586)
This PR updates our React InstantSearch and React InstantSearch Hooks template to use React 18. It also fixes a few issues that made projects based on our React InstantSearch Hooks templates not work in Codesandbox.
=> feat(templates): update react instantsearch web templates to react 18

e2e/__snapshots__/templates.test.js.snap, src/templates/React InstantSearch Hooks Native/App.tsx.hbs, src/templates/React InstantSearch Hooks Native/package.json
This PR fixes an issue with the React InstantSearch Hooks Native template, where the app shows an error if it generated with  more than one hit attribute to display.
It also updates the Expo CLI to fix an issue with how they check for TypeScript version (https://github.com/expo/expo-cli/pull/4439).
=> fix(templates): wrap React InstantSearch Hooks native hit attributes in `Fragment`
